### ISSUE TITLE
Missing files for reproducing results

### ISSUE THREAD

**Issue by szalata** [serbulent/TrainableRepresentationAnalysis#1]
When running PROBE with all the default arguments, I get an error due to a missing index file for mm15:
FileNotFoundError: [Errno 2] No such file or directory: '../data/preprocess/indexes/mm15_trainindex.csv'

**Comment by serbulent** [comment]
Hi,

Thanks for your interest. Sorry for the problem data.zip is updated please try again. More over you can find the official/stable repo at; https://github.com/kansil/PROBE . We advised use of the official repo for the PROBE.

**Comment by szalata** [comment]
Hello,
Thank's for the response. mm15_trainindex.csv still isn't there, from what I see.
Thank you for pointing me to the updated repo!

**Comment by serbulent** [comment]
Sorry file updated but the link was not. I just update it you can get it using https://drive.google.com/file/d/1elGfjI4jwzcjOBT6LoMnz-7DtdwPFV6i/view?usp=sharing link.

**Comment by szalata** [comment]
Thank you, that works.
